from enum import StrEnum


class SelectedService(StrEnum):
    STANDART_CLEANING = "STANDART_CLEANING"
    DEEP_CLEANING = "DEEP_CLEANING"
    CLEANING_MOVE = "CLEANING_MOVE"
    AFTER_CONSTRUCTION = "AFTER_CONSTRUCTION"
